---
kind: pipeline
name: default

steps:
- name: build
  image: golang:1.22.0
  volumes:
  - name: deps
    path: /go
  commands:
  - make

- name: test
  image: golang:1.22.0
  volumes:
  - name: deps
    path: /go
  commands:
  - make test

- name: linter
  image: golang:1.22.0
  volumes:
    - name: deps
      path: /go
  commands:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s
    - ./bin/golangci-lint run --timeout 5m
    - rm -r ./bin/

- name: telegram
  image: appleboy/drone-telegram
  settings:
    to: 790376882
    token:
      from_secret: telegram_token

volumes:
- name: deps
  host:
    path: /var/lib/cache/godeps/
