name: Golang

on:
  pull_request:
  push:
    branches: [main]

jobs:
  golang-push:
    if: github.event_name == 'push'
    permissions:
      contents: write
      pull-requests: write
      checks: write
    uses: depado/github-actions/.github/workflows/golang.yml@main

  golang-pr:
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
      checks: write
    uses: depado/github-actions/.github/workflows/golang.yml@main
